### ISSUE TITLE
[non-issue, note] great library.. found a nice use for it

### ISSUE THREAD

**Issue by warren-bank** [ashbeats/resolve-lnk#11]
Hi. I just thought you might like seeing how I recently added your library to my personal [fork](https://github.com/warren-bank/node-serve) of [`serve`](https://github.com/vercel/serve)

* a Node.js static file HTTP server
  - which I like a lot
  - and supports Range headers
    * ..that (for example) allow it to be used to serve large videos to Chromecast over a LAN w/ ability to fast-forward/rewind
* your library allows the HTTP server to detect and properly handle Windows shortcuts
  - to both files and directories
  - nesting directories in this way works too

I don't plan on making a pull request to the upstream `serve` project
* I made massive changes
  - couldn't resist.. it has a lot of spaghetti code
* it would be a lot of extra work
  - to revert those changes and extract a minimal patch
* I don't personally care if anybody else uses it
  - only letting you know about it because I wanted to thank you.. you wrote a great library! :)

**Comment by ashbeats** [comment]
@warren-bank Thank you warren!  I'm sorry for the terribly late response.
